/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ItemDAO;
import dao.LoginDAO;
import dao.SupplierDAO;
import dto.Item;
import dto.ItemTableModel;
import dto.Supplier;
import dto.SupplierTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class View extends javax.swing.JFrame {
    LoginDAO ct;
    SupplierDAO suppDAO;
    ItemDAO itemDAO;
    SupplierTableModel<Supplier> supplierModel;
    ItemTableModel<Item> itemModel;
    boolean addNewSupp = false;
    boolean addNewItem = false;
    final int SUCCESS = 1;
    
    /**
     * Creates new form LoginView
     */
    public View() throws Exception {
        initComponents();
        ct=new LoginDAO();
        suppDAO = new SupplierDAO();
        itemDAO = new ItemDAO();
        txtUser.setText("SE140871");
        txtPassword.setText("123456");
        int[] supplierTableIndexes = {0, 1, 2};
        String[] supplierTableHeader = {"Code", "Name", "Address"};
        supplierModel = new SupplierTableModel<Supplier>(supplierTableHeader, supplierTableIndexes);
        this.tblSupplier.setModel(supplierModel);
        int[] itemTableIndexes = {0, 1, 2, 3, 4, 5};
        String[] itemTableHeader = {"Code", "Name", "Supplier", "Unit", "Price", "Supplying"};
        itemModel = new ItemTableModel<Item>(itemTableHeader, itemTableIndexes);
        this.tblItem.setModel(itemModel);
        /////
        setComboBox();
        lockItemInput();
        lockSupplierInput();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSuppCode = new javax.swing.JTextField();
        txtSuppName = new javax.swing.JTextField();
        txtSuppAddress = new javax.swing.JTextField();
        ckbCollaborating = new javax.swing.JCheckBox();
        btnSuppAddNew = new javax.swing.JButton();
        btnSuppSave = new javax.swing.JButton();
        btnSuppDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        cbSupplier = new javax.swing.JComboBox<>();
        txtItemUnit = new javax.swing.JTextField();
        txtItemPrice = new javax.swing.JTextField();
        ckbSupplying = new javax.swing.JCheckBox();
        btnItemAddNew = new javax.swing.JButton();
        btnItemSave = new javax.swing.JButton();
        btnItemDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPanel.setMaximumSize(new java.awt.Dimension(450, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("User:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password:");

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setPreferredSize(new java.awt.Dimension(90, 30));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUser.setPreferredSize(new java.awt.Dimension(240, 30));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(240, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("ITEM MANAGEMENT");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(240, 240, 240))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel13)
                .addGap(60, 60, 60)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(loginPanel, "card2");

        homePanel.setPreferredSize(new java.awt.Dimension(800, 400));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 400));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 375));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Code:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Collaborating");

        txtSuppCode.setPreferredSize(new java.awt.Dimension(180, 30));

        txtSuppName.setPreferredSize(new java.awt.Dimension(180, 30));

        txtSuppAddress.setToolTipText("");
        txtSuppAddress.setPreferredSize(new java.awt.Dimension(180, 30));

        btnSuppAddNew.setText("Add New");
        btnSuppAddNew.setPreferredSize(new java.awt.Dimension(90, 30));
        btnSuppAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppAddNewActionPerformed(evt);
            }
        });

        btnSuppSave.setText("Save");
        btnSuppSave.setPreferredSize(new java.awt.Dimension(90, 30));
        btnSuppSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppSaveActionPerformed(evt);
            }
        });

        btnSuppDelete.setText("Delete");
        btnSuppDelete.setPreferredSize(new java.awt.Dimension(90, 30));
        btnSuppDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addComponent(btnSuppAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnSuppSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnSuppDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSuppName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbCollaborating))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSuppCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSuppName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSuppAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ckbCollaborating))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuppAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuppDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuppSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.setPreferredSize(new java.awt.Dimension(450, 380));
        tblSupplier.getTableHeader().setReorderingAllowed(false);
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Suppliers", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 375));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 375));

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItem.setPreferredSize(new java.awt.Dimension(450, 350));
        tblItem.getTableHeader().setReorderingAllowed(false);
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblItem);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Item code:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Item name:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Supplier:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Price:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Unit:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Supplying:");

        txtItemCode.setPreferredSize(new java.awt.Dimension(180, 30));

        txtItemName.setToolTipText("");
        txtItemName.setPreferredSize(new java.awt.Dimension(180, 30));

        cbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtItemUnit.setPreferredSize(new java.awt.Dimension(180, 30));

        txtItemPrice.setPreferredSize(new java.awt.Dimension(180, 30));

        btnItemAddNew.setText("Add New");
        btnItemAddNew.setPreferredSize(new java.awt.Dimension(90, 30));
        btnItemAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemAddNewActionPerformed(evt);
            }
        });

        btnItemSave.setText("Save");
        btnItemSave.setPreferredSize(new java.awt.Dimension(90, 30));
        btnItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemSaveActionPerformed(evt);
            }
        });

        btnItemDelete.setText("Delete");
        btnItemDelete.setPreferredSize(new java.awt.Dimension(90, 30));
        btnItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtItemUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckbSupplying)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnItemSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnItemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnItemAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtItemUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(ckbSupplying))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnItemAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItemSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Items", jPanel2);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(homePanel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        addNewItem = false;
        int pos = tblItem.getSelectedRow();
        if(pos == -1)
            return;
        txtItemCode.setText(tblItem.getValueAt(pos, 0).toString());
        txtItemName.setText(tblItem.getValueAt(pos, 1).toString());
        int selectedItem = 0;
        setComboBox();
        try 
        {
            for(Supplier  s : SupplierDAO.getAllSuppliers())
            {
                if(tblItem.getValueAt(pos, 2).toString().contains(s.getSupplierCode()))
                {
                    for(int i=0; i< cbSupplier.getItemCount(); i++)
                    {
                        if(cbSupplier.getItemAt(i).toString().contains(s.getSupplierCode()))
                            selectedItem = i;
                    }
                }
            }
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbSupplier.setSelectedIndex(selectedItem);
        txtItemUnit.setText(tblItem.getValueAt(pos, 3).toString());
        txtItemPrice.setText(tblItem.getValueAt(pos, 4).toString());
        ckbSupplying.setSelected(tblItem.getValueAt(pos, 5).toString().equalsIgnoreCase("true"));
        btnItemDelete.setEnabled(true);
        txtItemCode.setEnabled(false);
        /////
        unlockItemInput();
    }//GEN-LAST:event_tblItemMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            if(ct.checkLogin(this.txtUser.getText(), this.txtPassword.getText()))
            {
                ct.changePanel(getContentPane(), "card3");
                supplierModel.setData(suppDAO.loadSuppliers());
                itemModel.setData(itemDAO.loadItems());
            }
            else
            JOptionPane.showMessageDialog(this, "Login failed!!!");
        } catch (Exception ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSuppAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppAddNewActionPerformed
        addNewSupp = true;
        clearSupplierInfo();
        btnSuppDelete.setEnabled(false);
        txtSuppCode.setEnabled(true);
        /////
        unlockSupplierInput();
    }//GEN-LAST:event_btnSuppAddNewActionPerformed

    private void btnItemAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemAddNewActionPerformed
        addNewItem = true;
        setComboBox();
        clearItemInfo();
        btnItemDelete.setEnabled(false);
        txtItemCode.setEnabled(true);
        /////
        unlockItemInput();
    }//GEN-LAST:event_btnItemAddNewActionPerformed

    private void btnSuppSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppSaveActionPerformed
        String code = txtSuppCode.getText().toUpperCase().trim();
        String name = txtSuppName.getText().trim();
        String address = txtSuppAddress.getText().trim();
        boolean collaborating = ckbCollaborating.isSelected();
        if(!SupplierDAO.validateSupplierData(addNewSupp, code, name, address))
            return;
        Supplier s = new Supplier(code, name, address, collaborating);
        if(addNewSupp==true)
        {
            try 
            {
                if(SupplierDAO.getSupplierByCode(code)!=null)
                {
                    JOptionPane.showMessageDialog(this, "Duplicate code!");
                    return;
                }
                int result = SupplierDAO.insertSupplier(s);
                if(result==SUCCESS)
                {
                    supplierModel.getData().add(s);
                    this.tblSupplier.setModel(supplierModel);
                    JOptionPane.showMessageDialog(this, "Add successfully!");
                }
                else
                    JOptionPane.showMessageDialog(this, "Add failed!");
            }
            catch (Exception ex) 
            {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            int pos = tblSupplier.getSelectedRow();
            try 
            {              
                int result = SupplierDAO.updateSupplier(s);
                if(result==SUCCESS)
                {
                    supplierModel.getData().set(pos, s);
                    this.tblSupplier.setModel(supplierModel);
                    JOptionPane.showMessageDialog(this, "Update successfully!");
                }
                else
                    JOptionPane.showMessageDialog(this, "Update failed!");
            } 
            catch (Exception ex) 
            {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tblSupplier.updateUI();
        clearSupplierInfo();
        setComboBox();
        addNewSupp = false;
        /////
        lockSupplierInput();
    }//GEN-LAST:event_btnSuppSaveActionPerformed

    private void btnItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemSaveActionPerformed
        String code = txtItemCode.getText().toUpperCase().trim();
        String name = txtItemName.getText().trim();
        String unit = txtItemUnit.getText().trim();
        String price = txtItemPrice.getText().trim();
        int item = cbSupplier.getSelectedIndex();
        String supplier = cbSupplier.getItemAt(item);
        String supplierCode = null;
        try 
        {
            for(Supplier s : SupplierDAO.getAllSuppliers())
            {
                if(supplier.contains(s.getSupplierCode()))
                    supplierCode = s.getSupplierCode();
            }
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        boolean supplying = ckbSupplying.isSelected();
        if(!ItemDAO.validateItemData(addNewItem, code, name, unit, price))
            return;
        Item newItem = new Item(code, name, unit, Float.parseFloat(price), supplierCode, supplying);
//        Item itemDTB = new Item(code, name, unit, Float.parseFloat(price), supplierCode, supplying);
        if(addNewItem==true)
        {
            try 
            {
                if(ItemDAO.getItemByCode(code)!=null)
                {
                    JOptionPane.showMessageDialog(this, "Duplicate code!");
                    return;
                }              
                int result = ItemDAO.insertItem(newItem);
                if(result==SUCCESS)
                {
                    itemModel.getData().add(newItem);
                    this.tblItem.setModel(itemModel);
                    JOptionPane.showMessageDialog(this, "Add successfully!");
                }
                else
                    JOptionPane.showMessageDialog(this, "Add failed!");
            } 
            catch (Exception ex) 
            {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            int pos = tblItem.getSelectedRow();
            try 
            {
                int result = ItemDAO.updateItem(newItem);
                if(result==SUCCESS)
                {
                    itemModel.getData().set(pos, newItem);
                    this.tblItem.setModel(itemModel);
                    JOptionPane.showMessageDialog(this, "Update successfully!");
                }
                else
                    JOptionPane.showMessageDialog(this, "Update failed!");
            } 
            catch (Exception ex) 
            {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        tblItem.updateUI();
        clearItemInfo();
        addNewItem = false;
        /////
        lockItemInput();
    }//GEN-LAST:event_btnItemSaveActionPerformed

    private void btnSuppDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppDeleteActionPerformed
        int confirm;
        confirm = JOptionPane.showConfirmDialog(this, "Do you want to remove this supplier?");
        if(confirm == JOptionPane.YES_OPTION)
        {
            int selectedRow=tblSupplier.getSelectedRow();
            String code = tblSupplier.getValueAt(selectedRow, 0).toString();
            boolean check = false;
            try 
            {
                for (Item i : ItemDAO.getAllItems()) 
                {
                    if(i.getSupplier().equalsIgnoreCase(tblSupplier.getValueAt(selectedRow, 0).toString()))
                    {
                        check = true;
                    }
                }
                if(check == true)
                {
                    JOptionPane.showMessageDialog(this, "You can not remove this supplier!!!");
                }
                else
                {
                    int delete = SupplierDAO.deleteSupplier(code);
                    if(delete==SUCCESS)
                    {
                        supplierModel.getData().remove(selectedRow);
                    }
                    JOptionPane.showMessageDialog(this, "This supplier is removed!");
                }
            }   
            catch (Exception ex) 
            {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tblSupplier.updateUI();
        clearSupplierInfo();
        txtSuppCode.setEnabled(true);
        /////
        lockSupplierInput();
    }//GEN-LAST:event_btnSuppDeleteActionPerformed

    private void btnItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDeleteActionPerformed
        int confirm;
        confirm = JOptionPane.showConfirmDialog(this, "Do you want to remove this item?");
        if(confirm == JOptionPane.YES_OPTION)
        {
            String code = tblItem.getValueAt(tblItem.getSelectedRow(), 0).toString();
            try 
            {
                if(ItemDAO.deleteItem(code)==SUCCESS)
                {
                    itemModel.getData().remove(tblItem.getSelectedRow());
                    JOptionPane.showMessageDialog(this, "This item is removed!");
                }
            } 
            catch (Exception e) 
            {
                e.printStackTrace();
            }
        }
        tblItem.updateUI();
        clearItemInfo();
        /////
        lockItemInput();
    }//GEN-LAST:event_btnItemDeleteActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        addNewSupp = false;
        int pos = tblSupplier.getSelectedRow();
        if(pos == -1)
            return;
        Supplier curSupp;
        curSupp = supplierModel.getData().get(pos);
        this.txtSuppCode.setText(curSupp.getSupplierCode());
        this.txtSuppName.setText(curSupp.getSupplierName());
        this.txtSuppAddress.setText(curSupp.getSupplierAddress());
        this.ckbCollaborating.setSelected(curSupp.isCollaborating());
        btnSuppDelete.setEnabled(true);
        txtSuppCode.setEnabled(false);
        /////
        unlockSupplierInput();
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
//        clearItemInfo();
//        clearSupplierInfo();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    public void setComboBox()
    {
        cbSupplier.removeAllItems();
        try 
        {
            for (Supplier s : SupplierDAO.getAllSuppliers())
            {
                cbSupplier.addItem(s.getSupplierCode() + " - " + s.getSupplierName());
            }
        } 
        catch (Exception ex)
        {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void clearItemInfo()
    {
        txtItemCode.setText("");
        txtItemName.setText("");
        txtItemUnit.setText("");
        txtItemPrice.setText("");
        cbSupplier.setSelectedIndex(0);
        ckbSupplying.setSelected(false);
    }
    
    public void clearSupplierInfo()
    {
        txtSuppCode.setText("");
        txtSuppName.setText("");
        txtSuppAddress.setText("");
        ckbCollaborating.setSelected(false);
    }    
    
    private void lockItemInput()
    {
        txtItemCode.setEnabled(false);
        txtItemName.setEnabled(false);
        txtItemPrice.setEnabled(false);
        txtItemUnit.setEnabled(false);
        cbSupplier.setEnabled(false);
        ckbSupplying.setEnabled(false);
        btnItemSave.setEnabled(false);
        btnItemDelete.setEnabled(false);
    }
    
    private void unlockItemInput()
    {
        btnItemSave.setEnabled(true);
        txtItemName.setEnabled(true);
        txtItemPrice.setEnabled(true);
        txtItemUnit.setEnabled(true);
        cbSupplier.setEnabled(true);
        ckbSupplying.setEnabled(true);
    }
    
    private void lockSupplierInput()
    {
        txtSuppCode.setEnabled(false);
        txtSuppName.setEnabled(false);
        txtSuppAddress.setEnabled(false);
        ckbCollaborating.setEnabled(false);
        btnSuppSave.setEnabled(false);
        btnSuppDelete.setEnabled(false);
    }
    
    private void unlockSupplierInput()
    {
        btnSuppSave.setEnabled(true);
        txtSuppName.setEnabled(true);
        txtSuppAddress.setEnabled(true);
        ckbCollaborating.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try 
                {
                    new View().setVisible(true);
                } 
                catch (Exception ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItemAddNew;
    private javax.swing.JButton btnItemDelete;
    private javax.swing.JButton btnItemSave;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSuppAddNew;
    private javax.swing.JButton btnSuppDelete;
    private javax.swing.JButton btnSuppSave;
    private javax.swing.JComboBox<String> cbSupplier;
    private javax.swing.JCheckBox ckbCollaborating;
    private javax.swing.JCheckBox ckbSupplying;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtItemUnit;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSuppAddress;
    private javax.swing.JTextField txtSuppCode;
    private javax.swing.JTextField txtSuppName;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
